version: '3'

services:
   messaging-server:
      image: nats
      logging:
        driver: none
   tor-proxy:
      image: osminogin/tor-simple
      logging:
        driver: none
   database:
      image: mongo
      logging:
        driver: none
   database_seeder:
      build:
         context: .
         dockerfile: Dockerfile-mongoseeder
      logging:
         driver: none
      depends_on:
         - database
   database-ui:
      image: mongo-express
      logging:
        driver: none
      environment:
         ME_CONFIG_MONGODB_SERVER: database
      ports:
        - 15001:8081
   crawler:
      image: trandoshanio/crawler
      restart: unless-stopped
      environment:
         - TOR_PROXY=tor-proxy:9050
         - NATS_URI=nats://derek:pass@messaging-server:4222
         - FORBIDDEN_CONTENT_TYPES=application/octet-stream
      depends_on:
         - messaging-server
         - tor-proxy
   scheduler:
      image: trandoshanio/scheduler
      restart: unless-stopped
      environment:
         - NATS_URI=nats://derek:pass@messaging-server:4222
         - API_URI=http://api:8080
      depends_on:
         - messaging-server
         - api
   persister:
      image: trandoshanio/persister
      restart: unless-stopped
      environment:
         - MONGO_URI=mongodb://database:27017
         - NATS_URI=nats://derek:pass@messaging-server:4222
      depends_on:
         - messaging-server
         - database
   api:
      image: trandoshanio/api
      restart: unless-stopped
      environment:
         - MONGO_URI=mongodb://database:27017
      depends_on:
        - database
        - messaging-server
      ports:
        - 15002:8080
   feeder:
      image: trandoshanio/feeder
      environment:
         - NATS_URI=nats://derek:pass@messaging-server:4222
         - INITIAL_URI=something_here
      depends_on:
         - messaging-server
   dashboard:
      image: trandoshan-io/dashboard
      depends_on:
         - api
      ports:
         - 15003:80